#!/bin/sh

SCRIPTS_DIR="$HOME/Scripts"

if [ ! -d "$SCRIPTS_DIR" ]; then
  echo "Please enter a directory for the scripts"
  read -r SCRIPTS_DIR
  mkdir "$SCRIPTS_DIR"
fi

cargo build --release
mv target/release/jirarust "$SCRIPTS_DIR/jirarust"
